# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
 name = "Thales and Friends"  # A name for the link.
    url = "#thales"  # URL of the section.
    weight = 55  # Position of the link in the menu

[[main]]
  name = "Workshops"
  url = "#Workshops"
  weight = 54


[[main]]
 name = "Supervision"  # A name for the link.
    url = "#supervision"  # URL of the section.
    weight = 50  # Position of the link in the menu


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Recent Publications"
  url = "#featured"
  weight = 35


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
